apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecosort-flask-api
  labels:
    app: ecosort-flask-api
spec:
  selector:
    matchLabels:
      app: ecosort-flask-api
  replicas: 1
  template:
    metadata:
      labels:
        app: ecosort-flask-api
    spec:
      containers:
        - name: ecosort-flask-api
          image: ghcr.io/trthingnes/ecosort-flask-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              ephemeral-storage: 256M
              memory: 256M
              cpu: 100m
            requests:
              ephemeral-storage: 256M
              memory: 256M
              cpu: 100m
      imagePullSecrets:
        - name: github-registry-credentials
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: ecosort-flask-api
spec:
  selector:
    app: ecosort-flask-api
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: ecosort-flask-api
  labels:
    app.kubernetes.io/name: ecosort-flask-api
  annotations: {}
  namespace: kaist-ecosort
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods:
        - GET
      accessStrategies:
        - handler: allow
      service:
        name: ecosort-flask-api
        port: 8080
  service:
    name: ecosort-flask-api
    port: 8080
  host: ecosort.ede20ab.kyma.ondemand.com
