-- Table to store conversations
CREATE TABLE Conversation (
    conversation_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_name NVARCHAR(255) NOT NULL
);

-- Table to store messages
CREATE TABLE Message (
    message_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conversation_id INT,
    message_text NVARCHAR(1000) NOT NULL,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (conversation_id) REFERENCES Conversation(conversation_id)
);

-- Table to store responses
CREATE TABLE Response (
    response_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    message_id INT,
    response_text NVARCHAR(1000) NOT NULL,
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (message_id) REFERENCES Message(message_id)
);

-- Table to store keyword frequencies
CREATE TABLE KeywordFrequency (
    keyword_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    keyword NVARCHAR(255) NOT NULL,
    frequency INT NOT NULL,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
